from __future__ import annotations

import io
import json
import math
import random
import struct
import wave
from collections.abc import Sequence
from pathlib import Path

SYNTHETIC_CLASSES = ("steady_tone", "pulsed_tone", "broadband_texture")
SAMPLE_RATE = 16_000


def generate_samples(class_id: str, *, variant: int = 0, duration_seconds: float = 1.0) -> list[float]:
    if class_id not in SYNTHETIC_CLASSES:
        raise ValueError(f"unknown synthetic class: {class_id}")
    if variant < 0:
        raise ValueError("variant must be non-negative")
    sample_count = int(SAMPLE_RATE * duration_seconds)
    amplitude = 0.30 + (variant % 3) * 0.025
    frequency = 280.0 + variant * 31.0

    if class_id == "steady_tone":
        return [amplitude * math.sin(2 * math.pi * frequency * index / SAMPLE_RATE) for index in range(sample_count)]
    if class_id == "pulsed_tone":
        pulse_frames = int(SAMPLE_RATE * 0.10)
        return [
            amplitude * math.sin(2 * math.pi * (frequency + 80) * index / SAMPLE_RATE)
            if (index // pulse_frames) % 2 == 0
            else 0.0
            for index in range(sample_count)
        ]

    generator = random.Random(7_900 + variant)
    return [generator.uniform(-amplitude, amplitude) for _ in range(sample_count)]


def wav_bytes(samples: Sequence[float], *, sample_rate: int = SAMPLE_RATE) -> bytes:
    output = io.BytesIO()
    with wave.open(output, "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(sample_rate)
        pcm = b"".join(
            struct.pack("<h", max(-32768, min(32767, round(value * 32767)))) for value in samples
        )
        handle.writeframes(pcm)
    return output.getvalue()


def generate_fixture_bytes(class_id: str, *, variant: int = 0) -> bytes:
    return wav_bytes(generate_samples(class_id, variant=variant))


def write_fixture_set(output_dir: str | Path) -> list[Path]:
    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    manifest = {
        "schema_version": 1,
        "provenance": "Deterministically generated by acoustic_sandbox.synthetic; no recorded audio.",
        "sample_rate_hz": SAMPLE_RATE,
        "files": [],
    }
    for class_id in SYNTHETIC_CLASSES:
        path = destination / f"{class_id}.wav"
        payload = generate_fixture_bytes(class_id)
        path.write_bytes(payload)
        written.append(path)
        manifest["files"].append({"path": path.name, "synthetic_class": class_id, "bytes": len(payload)})
    manifest_path = destination / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    written.append(manifest_path)
    return written
